version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ../../services/nginx
      args:
        - NGINX_VER=latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - /etc/localtime:/etc/localtime:cached
      - ../../logs/nginx:/var/log/nginx:cached
      - ../../services/nginx/conf.d:/etc/nginx/conf.d:cached
      - ../../wwwroot:/wwwroot:cached
      #- ../../services/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      ## SSL 证书目录挂载
      - ../../services/nginx/certs:/etc/nginx/certs:cached
    networks:
      dev: 
        ipv4_address: 172.19.0.2


  php72:
    container_name: php72
    image: registry.cn-shanghai.aliyuncs.com/ylcode/php:7.2-fpm
    restart: always
    depends_on: 
      - nginx
    volumes:
      - ../../wwwroot:/wwwroot:cached
    networks:
        dev: 
          ipv4_address: 172.19.0.10

  php70:
    container_name: php70
    image: registry.cn-shanghai.aliyuncs.com/ylcode/php:7.0-fpm
    restart: always
    depends_on: 
      - nginx
    volumes:
      - ../../wwwroot:/wwwroot:cached
    networks:
        dev: 
          ipv4_address: 172.19.0.11
  php56:
    container_name: php56
    image: registry.cn-shanghai.aliyuncs.com/ylcode/php:5.6-fpm
    restart: always
    depends_on:
      - nginx
    volumes:
      - ../../wwwroot:/wwwroot:cached
    networks:
        dev:
          ipv4_address: 172.19.0.12

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    depends_on: 
      - php72
      - php70
      - php56
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      # - ../../services/mysql/conf:/etc/mysql  
      - ../../data/mysql/data:/var/lib/mysql:rw
    networks:
      dev: 
        ipv4_address: 172.19.0.20

  redis:
    container_name: redis
    build:
      context: ../../services/redis
      args:
        - REDIS_VER=5
    ports:
      - "6379:6379"
    volumes:
      - ../../services/redis/redis.conf:/usr/local/etc/redis/redis.conf:cached
      - ../../data/redis:/data:cached
      - ../../logs/redis:/var/log/:cached
    networks:
      dev: 
        ipv4_address: 172.19.0.21
    restart: always


networks:
  dev:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/16